### ISSUE TITLE
ptpwd doesn't compile on MacOS Monterey 12.3[BUG]

### ISSUE THREAD

**Issue by ewjannece** [jszczerbinsky/ptSh#51]
Looking at the makefile, there doesn't seem to be anything to figure out what kind of system it will be compiled on. 
Somethings compile with warnings and others error from the linux headers in the main.c code. 
Downloading a fresh repo copy and running make give the following error: 

```
mkdir -p build
rm -rf build/*
mkdir -p build/bin
mkdir -p build/share
mkdir -p build/share/ptSh
gcc src/common/*.c src/ptls/*.c -lm -o build/bin/ptls
src/ptls/fields.c:46:32: warning: format specifies type 'int' but the argument has type '__darwin_ino64_t' (aka 'unsigned long long') [-Wformat]
  sprintf(fields->inode, "%d", file->stats->st_ino);
                          ~~   ^~~~~~~~~~~~~~~~~~~
                          %llu
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
1 warning generated.
gcc src/common/*.c src/ptpwd/*.c -lm -o build/bin/ptpwd
src/ptpwd/main.c:1:10: fatal error: 'linux/limits.h' file not found
#include <linux/limits.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [all] Error 1
```

System Info
```
gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

uname -a 
Darwin genes-iMac-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

```

**Comment by jszczerbinsky** [comment]
Duplicate: https://github.com/jszczerbinsky/ptSh/issues/47
